/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 earth.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({onEarthClick, ...props}) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  const earthRef = useRef()

  // Rotate the model continuously
  useFrame((state, delta) => {
    earthRef.current.rotation.y += delta * 0.5 // adjust speed here
  })

  return (
    <group ref={earthRef} {...props} dispose={null} onClick={onEarthClick}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} scale={2} />
    </group>
  )
}

useGLTF.preload('/earth.gltf')
